import Head from "next/head";
import Image from "next/image";
import Feed from "../components/Feed";
import Upload from "../components/Upload";
import { AuthContext } from "../context/auth";
import { useRouter } from "next/dist/client/router";
import { useContext } from "react";

export default function Home() {
  const { user } = useContext(AuthContext);

  const Redirect = () => {
    const router = useRouter();
    router.push("/login");
    return null;
  };

  return (
    <div className="">
      <Head>
        <title>Reels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user?.uid ? <Feed /> : <Redirect />}
      <Feed></Feed>
    </div>
  );
}
